const DB_KEY='shuttool_v2_db', SESSION_KEY='shuttool_v2_session';
const seed={users:[
{id:'admin1',name:'FUTA Transport Admin',email:'admin@futa.shuttool.demo',password:'admin123',role:'admin',school:'FUTA',status:'approved'},
{id:'stu1',name:'Joseph',email:'student@shuttool.demo',password:'student123',role:'student',school:'FUTA',status:'approved',demoBalance:2000,credit:300},
{id:'drv1',name:'Adewale',email:'driver@shuttool.demo',password:'driver123',role:'driver',school:'FUTA',status:'approved',demoBalance:4850},
{id:'drv2',name:'Emeka',email:'pending.driver@shuttool.demo',password:'driver123',role:'driver',school:'FUTA',status:'pending',demoBalance:0}],
claims:[{id:'c1',studentId:'stu1',driverId:'drv1',amount:300,fare:200,paid:500,status:'confirmed',createdAt:'2026-09-29T11:42:00Z'}],
transactions:[{id:'t1',userId:'stu1',type:'credit',amount:300,title:'Change credit',detail:'Driver confirmed · Today, 12:42 PM',status:'confirmed'}, {id:'t2',userId:'stu1',type:'fare',amount:-200,title:'Digital fare',detail:'Approved · Today, 11:30 AM',status:'confirmed'}],
issues:[{id:'i1',studentId:'stu1',title:'Fare / change dispute',text:'Demo issue: student reports that a confirmed change claim needs review.',status:'open',createdAt:'2026-09-29T12:50:00Z'}]};
function db(){let x=localStorage.getItem(DB_KEY);if(!x){localStorage.setItem(DB_KEY,JSON.stringify(seed));return structuredClone(seed)}return JSON.parse(x)}
function save(x){localStorage.setItem(DB_KEY,JSON.stringify(x))}
function session(){const id=localStorage.getItem(SESSION_KEY);return id?db().users.find(u=>u.id===id):null}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return '₦'+Number(n||0).toLocaleString()}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.add('hidden'),2500)}
function setSession(id){localStorage.setItem(SESSION_KEY,id)}
function logout(){localStorage.removeItem(SESSION_KEY);render()}
function reset(){localStorage.setItem(DB_KEY,JSON.stringify(seed));localStorage.removeItem(SESSION_KEY);render();toast('Demo reset.')}
function header(user){return `<header class="top"><div class="logo">SHUTTOOL<small>University shuttle payments</small></div>${user?`<div class="top-right"><span class="role-pill">${esc(user.school)} · ${esc(user.role)}</span><button class="btn outline" onclick="logout()">Sign out</button></div>`:''}</header>`}
function landing(){return `${header(null)}<main class="shell"><section class="hero"><div><div class="eyebrow">FUTA partner demo</div><h1>University shuttle payments, without the lost change.</h1><p>Record cash change owed, get driver confirmation, and carry the confirmed credit to your next approved shuttle.</p><div class="hero-actions"><button class="btn blue" onclick="showAuth('signup')">Create account</button><button class="btn outline" onclick="showAuth('login')">Sign in</button></div></div><div class="hero-note"><div class="small">DEMO FLOW</div><strong>₦300</strong><div class="small">confirmed change credit</div><button class="btn soft" style="margin-top:14px;width:100%" onclick="showAuth('signup')">Start demo</button></div></section><div class="card"><h3>How SHUTTOOL works</h3><div class="grid"><div><b>1. Identify</b><p class="muted small">Student scans the driver's QR.</p></div><div><b>2. Record</b><p class="muted small">Student enters fare and amount paid; owed change is calculated.</p></div><div><b>3. Confirm</b><p class="muted small">Driver confirms the claim and the credit becomes usable.</p></div></div></div></main>`}
function auth(mode='signup',role='student'){return `${header(null)}<main class="shell auth-wrap"><div class="card auth"><div class="eyebrow">SHUTTOOL · FUTA</div><h2>${mode==='signup'?'Create your account':'Sign in'}</h2><p class="muted">${mode==='signup'?'Choose your role and continue.':'Use your demo credentials or an account you created.'}</p>${mode==='signup'?signupForm(role):loginForm()}<div style="margin-top:15px;text-align:center"><button class="btn outline" onclick="showAuth('${mode==='signup'?'login':'signup'}')">${mode==='signup'?'Already have an account? Sign in':'Need an account? Create one'}</button></div></div></main>`}
function signupForm(role){return `<form onsubmit="createAccount(event)"><label>Full name<input id="name" required placeholder="e.g. Joseph Matthew"></label><label>Email<input id="email" type="email" required placeholder="you@example.com"></label><label>Password<input id="password" type="password" minlength="6" required></label><label>Account type</label><div class="role-grid">${[['student','Student','Pay fares & manage credits'],['driver','Driver','Confirm change claims'],['admin','Admin','Manage FUTA drivers & issues']].map(([r,t,d])=>`<label class="role-card ${role===r?'selected':''}"><input type="radio" name="role" value="${r}" ${role===r?'checked':''} onchange="refreshAuthRole()"><strong>${t}</strong><span>${d}</span></label>`).join('')}</div><div id="roleFields">${roleFields(role)}</div><button class="btn primary" type="submit">Create account</button><div class="helper">Demo note: public admin creation is protected by an admin access code. In production, admin accounts should be provisioned by the institution.</div></form>`}
function roleFields(role){if(role==='driver')return `<label>School<select id="school"><option value="FUTA">FUTA</option></select></label><div class="notice">FUTA is the partner school for this demo. Driver approval will be handled by the FUTA admin.</div>`;if(role==='admin')return `<label>School<select id="school"><option value="FUTA">FUTA</option></select></label><label>Admin access code<input id="adminCode" placeholder="Demo: FUTA-ADMIN"></label>`;return `<label>School<select id="school"><option value="FUTA">FUTA</option></select></label>`}
function refreshAuthRole(){const r=document.querySelector('input[name=role]:checked').value;document.getElementById('roleFields').innerHTML=roleFields(r);document.querySelectorAll('.role-card').forEach(x=>x.classList.remove('selected'));document.querySelector(`input[value="${r}"]`).parentElement.classList.add('selected')}
function loginForm(){return `<form onsubmit="doLogin(event)"><label>Email<input id="loginEmail" type="email" required></label><label>Password<input id="loginPassword" type="password" required></label><button class="btn primary" type="submit">Sign in</button><div class="helper"><b>Demo accounts</b><br>Student: student@shuttool.demo / student123<br>Driver: driver@shuttool.demo / driver123<br>Admin: admin@futa.shuttool.demo / admin123</div></form>`}
function createAccount(e){e.preventDefault();const f=e.target,r=f.querySelector('input[name=role]:checked').value;const d=db(),email=f.querySelector('#email').value.trim().toLowerCase();if(d.users.some(u=>u.email===email))return toast('An account with that email already exists.');if(r==='admin'&&f.querySelector('#adminCode')?.value!=='FUTA-ADMIN')return toast('Invalid admin access code.');const school=f.querySelector('#school')?.value||'FUTA';const u={id:r[0]+Date.now(),name:f.querySelector('#name').value.trim(),email,password:f.querySelector('#password').value,role:r,school,status:r==='driver'?'pending':'approved',demoBalance:r==='student'?2000:r==='driver'?4850:0,credit:0};d.users.push(u);save(d);setSession(u.id);toast(r==='driver'?'Account created. Waiting for FUTA admin approval.':'Account created.');render()}
function doLogin(e){e.preventDefault();const d=db(),email=document.getElementById('loginEmail').value.trim().toLowerCase(),p=document.getElementById('loginPassword').value,u=d.users.find(x=>x.email===email&&x.password===p);if(!u)return toast('Invalid email or password.');setSession(u.id);render()}
function appNav(){return ''}
function student(user){const d=db(),claims=d.claims.filter(c=>c.studentId===user.id).slice().reverse(),tx=d.transactions.filter(t=>t.userId===user.id).slice().reverse();return `${header(user)}<main class="shell">${appNav('student')}<div class="page-head"><div><div class="eyebrow">Student dashboard</div><h2>Good afternoon, ${esc(user.name)}</h2><p class="muted">Use a driver's QR to identify the approved shuttle before recording change.</p></div><div class="stat"><div class="label">Demo wallet balance</div><div class="value">${money(user.demoBalance)}</div></div></div><div class="feature-row four"><button class="feature active" onclick="studentAction('scan')"><div class="icon">⌁</div><strong>Scan QR</strong><span>Identify a driver</span></button><button class="feature" onclick="studentAction('change')"><div class="icon">₦</div><strong>Request change</strong><span>Record cash change owed</span></button><button class="feature" onclick="studentAction('wallet')"><div class="icon">+</div><strong>Fund wallet</strong><span>Transfer money from your bank</span></button><button class="feature" onclick="studentAction('issue')"><div class="icon">!</div><strong>Transaction issue</strong><span>Report a problem</span></button></div><div id="studentAction">${studentScan(user)}</div><div class="grid two"><div class="card"><div class="eyebrow">Change credit</div><h3>My credits</h3><div class="credit">${money(user.credit)}</div><div class="small muted">available confirmed credit</div><div class="timeline"><div class="step done"></div><div class="step ${claims.some(c=>c.status==='pending')?'current':'done'}"></div><div class="step"></div></div><div class="small muted" style="display:flex;justify-content:space-between"><span>Claimed</span><span>Confirmed</span><span>Usable</span></div></div><div class="card"><div class="eyebrow">Activity</div><h3>Recent transactions</h3><div class="list">${tx.length?tx.map(t=>`<div class="row"><div class="row-main"><div class="row-title">${esc(t.title)}</div><div class="row-sub">${esc(t.detail)}</div></div><strong class="${t.amount>=0?'money-green':'money-red'}">${t.amount>=0?'+':''}${money(t.amount)}</strong></div>`).join(''):'<div class="empty">No transactions yet.</div>'}</div></div></div><div class="card"><h3>My change claims</h3><div class="list">${claims.length?claims.map(c=>{const dr=d.users.find(u=>u.id===c.driverId);return `<div class="row"><div><div class="row-title">${money(c.amount)} change · ${esc(dr?.name||'Driver')}</div><div class="row-sub">Fare ${money(c.fare)} · Paid ${money(c.paid)}</div></div><span class="badge ${c.status}">${c.status}</span></div>`}).join(''):'<div class="empty">No change claims yet.</div>'}</div></div></main>`}
function studentScan(user){return `<div class="card"><h3>Scan driver's QR</h3><p class="muted">Only drivers have QR codes. Scan the approved driver's QR before making a change claim.</p><div class="scanner"><div class="scanner-box" id="reader"><div class="muted small">Camera scanner ready</div></div><div><div id="selectedDriver" class="driver-card"><b>No driver selected</b><div class="small muted" style="margin-top:5px">Use camera scan or the demo button.</div></div><button class="btn blue" style="margin-top:12px;width:100%" onclick="demoScan()">Demo scan approved driver</button><button class="btn outline" style="margin-top:8px;width:100%" onclick="startScanner()">Use camera</button></div></div></div>`}
function studentChange(user,driverId){const d=db(),drivers=d.users.filter(u=>u.role==='driver'&&u.school===user.school&&u.status==='approved');return `<div class="card"><h3>Request change</h3><p class="muted">Enter the fare and what you actually paid. SHUTTOOL calculates the change owed.</p><form onsubmit="submitClaim(event)"><input type="hidden" id="claimDriver" value="${driverId||''}"><label>Driver<select id="driverSelect" onchange="document.getElementById('claimDriver').value=this.value"><option value="">Select approved driver</option>${drivers.map(x=>`<option value="${x.id}" ${x.id===driverId?'selected':''}>${esc(x.name)} · ${esc(x.school)}</option>`).join('')}</select></label><div class="form-grid"><label>Fare<input id="fare" type="number" min="0" required placeholder="200"></label><label>Amount paid<input id="paid" type="number" min="0" required placeholder="500"></label></div><div id="changePreview" class="notice">Change owed: ₦0</div><button class="btn primary" type="submit">Request change credit</button></form></div>`}
function studentIssue(user){const d=db(),tx=d.transactions.filter(t=>t.userId===user.id);return `<div class="card"><h3>Report a transaction issue</h3><p class="muted">Use this for a disputed fare, wrong credit, or an issue with a driver confirmation.</p><form onsubmit="submitIssue(event)"><label>Transaction<select id="issueTx">${tx.map(t=>`<option value="${t.id}">${esc(t.title)} · ${money(t.amount)}</option>`).join('')}</select></label><label>What happened?<textarea id="issueText" rows="4" required placeholder="Explain the issue briefly..."></textarea></label><button class="btn primary">Submit issue</button></form></div>`}
function studentWallet(user){return `<div class="card wallet-card"><div class="eyebrow">Wallet</div><div class="wallet-head"><div><h3>Fund your SHUTTOOL wallet</h3><p class="muted">In the full product, you can transfer money from your bank into your wallet. This demo simulates that flow.</p></div><div class="wallet-balance"><span>Current balance</span><strong>${money(user.demoBalance)}</strong></div></div><div class="bank-transfer"><div><strong>Bank transfer</strong><p class="small muted">Use these demo details to simulate funding from another bank.</p></div><div class="bank-grid"><div><span>Bank</span><strong>SHUTTOOL Demo Bank</strong></div><div><span>Account name</span><strong>${esc(user.name)} · SHUTTOOL Wallet</strong></div><div><span>Account number</span><strong>0123456789</strong></div></div><div class="notice">Demo only — no real money is transferred. In production, this would connect to a payment/bank transfer provider.</div><button class="btn green" onclick="fundDemoWallet(1000)">Add ₦1,000 demo funds</button></div></div>`}
function fundDemoWallet(amount){const u=session(),d=db(),live=d.users.find(x=>x.id===u.id);if(!live)return;live.demoBalance=Number(live.demoBalance||0)+amount;d.transactions.push({id:'t'+Date.now(),userId:live.id,type:'funding',amount,title:'Wallet funding',detail:`Demo bank transfer · ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`,status:'confirmed'});save(d);toast(`${money(amount)} added to your demo wallet.`);render()}
function studentAction(type){const u=session();if(type==='scan'){document.getElementById('studentAction').innerHTML=studentScan(u);setTimeout(()=>startScanner(),80)}if(type==='change')document.getElementById('studentAction').innerHTML=studentChange(u,window.__selectedDriver||'');if(type==='wallet')document.getElementById('studentAction').innerHTML=studentWallet(u);if(type==='issue')document.getElementById('studentAction').innerHTML=studentIssue(u)}
function demoScan(){const d=db(),dr=d.users.find(u=>u.role==='driver'&&u.school==='FUTA'&&u.status==='approved');if(!dr)return toast('No approved FUTA driver is available in this demo.');window.__selectedDriver=dr.id;document.getElementById('selectedDriver').innerHTML=`<b>Driver identified: ${esc(dr.name)}</b><div class="small muted" style="margin-top:5px">${esc(dr.school)} · Approved driver</div><button class="btn green" style="margin-top:10px;width:100%" onclick="studentAction('change')">Continue to request change</button>`;toast('Approved driver identified.')}
function startScanner(){
  const readerEl=document.getElementById('reader');
  if(!readerEl)return;
  if(!window.Html5Qrcode)return toast('Camera scanner is loading. Try again in a moment.');
  if(window.__qrReader){try{window.__qrReader.stop().catch(()=>{});}catch(e){}}
  readerEl.innerHTML='';
  const reader=new Html5Qrcode('reader');
  window.__qrReader=reader;
  const config={fps:10,qrbox:{width:230,height:230}};
  const onScan=txt=>{
    try{
      const p=JSON.parse(txt),d=db(),dr=d.users.find(u=>u.id===p.driverId&&u.role==='driver'&&u.school===p.school&&u.status==='approved');
      if(!dr){toast('QR is not an approved FUTA SHUTTOOL driver.');return;}
      window.__selectedDriver=dr.id;
      reader.stop().catch(()=>{});
      window.__qrReader=null;
      const selected=document.getElementById('selectedDriver');
      if(selected)selected.innerHTML=`<b>Driver identified: ${esc(dr.name)}</b><div class="small muted" style="margin-top:5px">${esc(dr.school)} · Approved driver</div><button class="btn green" style="margin-top:10px;width:100%" onclick="studentAction('change')">Continue to request change</button>`;
      toast('Driver QR verified.');
    }catch(e){toast('Invalid SHUTTOOL QR.');}
  };
  reader.start({facingMode:{ideal:'environment'}},config,onScan,()=>{}).catch(()=>{
    window.__qrReader=null;
    readerEl.innerHTML='<div class="small muted" style="padding:20px;text-align:center">Camera could not be opened. Check browser camera permission and use HTTPS. You can still use Demo scan for the pitch.</div>';
    toast('Camera access was unavailable.');
  });
}

function submitClaim(e){e.preventDefault();const u=session(),driver=document.getElementById('claimDriver').value,fare=Number(document.getElementById('fare').value),paid=Number(document.getElementById('paid').value),amount=paid-fare;if(!driver)return toast('Select an approved driver.');if(amount<=0)return toast('There is no change owed on this payment.');const d=db();d.claims.push({id:'c'+Date.now(),studentId:u.id,driverId:driver,amount,fare,paid,status:'pending',createdAt:new Date().toISOString()});d.transactions.push({id:'t'+Date.now(),userId:u.id,type:'claim',amount,title:'Change claim',detail:`Awaiting driver confirmation · ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`,status:'pending'});save(d);toast(`₦${amount.toLocaleString()} change claim sent to driver.`);render()}
function updatePreview(){const fare=Number(document.getElementById('fare')?.value||0),paid=Number(document.getElementById('paid')?.value||0);const p=document.getElementById('changePreview');if(p)p.textContent=`Change owed: ${money(Math.max(0,paid-fare))}`}
document.addEventListener('input',e=>{if(e.target.id==='fare'||e.target.id==='paid')updatePreview()});
function driver(user){const d=db(),claims=d.claims.filter(c=>c.driverId===user.id).slice().reverse();return `${header(user)}<main class="shell">${appNav('driver')}<div class="page-head"><div><div class="eyebrow">Driver dashboard</div><h2>Welcome, ${esc(user.name)}</h2><p class="muted">Your QR identifies you to students. Approve only claims that match the cash transaction.</p></div><button class="btn blue" onclick="openQR('${user.id}')">Show my QR</button></div><div class="grid"><div class="stat"><div class="label">Account balance</div><div class="value">${money(user.demoBalance)}</div></div><div class="stat"><div class="label">School</div><div class="value" style="font-size:22px">${esc(user.school)}</div></div><div class="stat"><div class="label">Pending claims</div><div class="value">${claims.filter(c=>c.status==='pending').length}</div></div></div><div class="card"><h3>Your driver QR</h3><p class="muted">Students scan this code to identify you before creating a change claim.</p><button class="btn soft" onclick="openQR('${user.id}')">Open QR</button></div><div class="card"><h3>Change claims</h3><div class="list">${claims.length?claims.map(c=>{const st=d.users.find(x=>x.id===c.studentId);return `<div class="row"><div><div class="row-title">${money(c.amount)} change from ${esc(st?.name||'Student')}</div><div class="row-sub">Fare ${money(c.fare)} · Paid ${money(c.paid)}</div></div><div class="actions"><span class="badge ${c.status}">${c.status}</span>${c.status==='pending'?`<button class="btn green" onclick="driverDecision('${c.id}','confirmed')">Confirm</button><button class="btn red" onclick="driverDecision('${c.id}','rejected')">Reject</button>`:''}</div></div>`}).join(''):'<div class="empty">No pending claims. You are caught up.</div>'}</div></div></main>`}
function driverDecision(id,status){const d=db(),c=d.claims.find(x=>x.id===id),u=session();if(!c||c.driverId!==u.id)return; c.status=status;const st=d.users.find(x=>x.id===c.studentId);if(status==='confirmed'&&st){st.credit=Number(st.credit||0)+Number(c.amount);d.transactions.push({id:'t'+Date.now(),userId:st.id,type:'credit',amount:c.amount,title:'Change credit',detail:`Driver confirmed · ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`,status:'confirmed'})}save(d);toast(status==='confirmed'?'Claim confirmed. Student credit updated.':'Claim rejected.');render()}
function admin(user){
  const d=db();
  const drivers=d.users.filter(u=>u.role==='driver'&&u.school===user.school);
  const pending=drivers.filter(u=>u.status==='pending');
  const issues=d.issues.filter(i=>{const st=d.users.find(u=>u.id===i.studentId);return st?.school===user.school;}).slice().reverse();
  return `${header(user)}<main class="shell">
    <div class="page-head">
      <div><div class="eyebrow">Transport office · ${esc(user.school)}</div><h2>Admin control centre</h2><p class="muted">Approve registered drivers and handle student-reported transaction issues.</p></div>
    </div>
    <div class="grid two">
      <div class="card"><h3>Driver approval queue</h3><p class="muted small">Only drivers registered under ${esc(user.school)} appear here.</p><div class="list">${drivers.length?drivers.map(x=>`<div class="row"><div><div class="row-title">${esc(x.name)}</div><div class="row-sub">${esc(x.email)} · ${esc(x.school)}</div></div><div class="actions"><span class="badge ${x.status}">${x.status}</span>${x.status==='pending'?`<button class="btn green" onclick="adminDecision('${x.id}','approved')">Approve</button><button class="btn red" onclick="adminDecision('${x.id}','rejected')">Reject</button>`:''}</div></div>`).join(''):'<div class="empty">No drivers found.</div>'}</div></div>
      <div class="card"><h3>Student transaction issues</h3><p class="muted small">Only issues submitted by students are shown to the transport admin.</p><div class="list">${issues.length?issues.map(i=>{const st=d.users.find(x=>x.id===i.studentId);return `<div class="row"><div><div class="row-title">${esc(i.title)}</div><div class="row-sub">${esc(st?.name||'Student')} · ${esc(i.text)}</div></div><div class="actions"><span class="badge ${i.status}">${i.status}</span>${i.status==='open'?`<button class="btn green" onclick="resolveIssue('${i.id}')">Resolve</button>`:''}</div></div>`}).join(''):'<div class="empty">No student issues reported.</div>'}</div></div>
    </div>
  </main>`;
}
function adminDecision(id,status){const d=db(),u=session(),x=d.users.find(x=>x.id===id&&x.school===u.school&&x.role==='driver');if(!x)return;x.status=status;save(d);toast(`Driver ${status}.`);render()}
function submitIssue(e){e.preventDefault();const u=session(),d=db();d.issues.push({id:'i'+Date.now(),studentId:u.id,title:'Student transaction issue',text:document.getElementById('issueText').value,status:'open',createdAt:new Date().toISOString()});save(d);toast('Issue sent to the FUTA admin.');render()}
function resolveIssue(id){const d=db(),i=d.issues.find(x=>x.id===id);if(i)i.status='resolved';save(d);toast('Issue resolved.');render()}
function openQR(id){const d=db(),u=d.users.find(x=>x.id===id);document.getElementById('modal').innerHTML=`<div class="modal-box"><button class="close" onclick="closeModal()">×</button><div class="eyebrow">DRIVER QR</div><h2>${esc(u.name)}</h2><p class="muted">${esc(u.school)} · Approved driver</p><div id="qr" class="qr-holder"></div><p class="small muted">Students scan this code to identify this driver.</p></div>`;document.getElementById('modal').classList.remove('hidden');new QRCode(document.getElementById('qr'),{text:JSON.stringify({app:'SHUTTOOL',driverId:u.id,school:u.school,name:u.name}),width:220,height:220})}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function renderRole(role){const u=session();if(!u)return;render()}
function pendingDriver(u){return `${header(u)}<main class="shell"><div class="card centered"><span class="badge pending">Waiting for approval</span><h2>Driver account submitted</h2><p class="muted">Your ${esc(u.school)} driver account is waiting for approval by the ${esc(u.school)} transport admin.</p><div class="notice">Once approved, you can display your driver QR and respond to student change claims.</div></div></main>`}
function driverPreview(){return `<main class="shell"><div class="card centered"><h2>Driver view</h2><p class="muted">Sign in with a driver account to see this dashboard.</p></div></main>`}
function adminPreview(){return `<main class="shell"><div class="card centered"><h2>Admin view</h2><p class="muted">Sign in with the FUTA admin account to manage approvals and issues.</p></div></main>`}
function showAuth(m){document.getElementById('app').innerHTML=auth(m,'student')}
function render(){const u=session();document.getElementById('app').innerHTML=u?(u.role==='student'?student(u):u.role==='driver'?(u.status==='approved'?driver(u):pendingDriver(u)):admin(u)):landing()}
window.showAuth=showAuth;window.refreshAuthRole=refreshAuthRole;window.createAccount=createAccount;window.doLogin=doLogin;window.renderRole=renderRole;window.studentAction=studentAction;window.demoScan=demoScan;window.startScanner=startScanner;window.submitClaim=submitClaim;window.driverDecision=driverDecision;window.adminDecision=adminDecision;window.submitIssue=submitIssue;window.resolveIssue=resolveIssue;window.openQR=openQR;window.closeModal=closeModal;window.logout=logout;window.reset=reset;window.updatePreview=updatePreview;
const modal=document.createElement('div');modal.id='modal';modal.className='modal hidden';modal.onclick=e=>{if(e.target.id==='modal')closeModal()};document.body.appendChild(modal);render();
